import { Roboto } from 'next/font/google';
import './globals.css';
import Header from '../components/layout/Header';

import { AppProvider } from '../components/AppContext';

const roboto = Roboto({ subsets: ['latin'], weight: ['400', '500', '700'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  const year = new Date().getFullYear();
  return (
    <html lang="en">
      <body className={roboto.className}>
        <main className="max-w-4xl mx-auto p-4">
          <AppProvider>
          <Header />
          {children}
          <footer className="border-t p-8 text-center text-gray-500">
            &copy; {year}
            <span className="ml-2">All rights reserved</span>
          </footer>
          </AppProvider>
        </main>
      </body>
    </html>
  );
}
